name: arcore_example
description: A new project to learn how to use ARCore in your Flutter App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ar_flutter_plugin: ^0.6.2  
  google_fonts:
  animated_text_kit: ^4.2.2
  card_swiper: ^2.0.4
  auto_size_text: ^3.0.0
  gallery_saver: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/AR-Icon.png"
  adaptive_icon_foreground: "assets/icon-foreground.png"
  adaptive_icon_background: "#ffffff"

flutter:

  uses-material-design: true

  assets:
    - assets/triangle.png
    - assets/Chicken_01/
    - assets/sofa/
    - assets/images/
